# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57f01ebd39dcb43413a2981337baadc3c2ea0981306d16ee10ae1d5eeaba8f2ada119e3de9d162bbf076409f679162fe99b7dfb6a182aae288b46bf53b463706

test:
  secret_key_base: 6b4a12e4316999a852d509a9edf417a784565488e3f23a23bcc6e96d302fe9942a22a50bf73160d4ab248225482798faf907c202a352fd01618b6b0470f998e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
